const ActionTypes = {
    SAVE_USER: 'SAVE_USER',
    SAVE_REQUIREMENTS: 'SAVE_REQUIREMENTS',
    SAVE_REQUIREMENT: 'SAVE_REQUIREMENT',
    UPDATE_USER: 'SAVE_USER',
    UPDATE_REQUIREMENT: 'UPDATE_REQUIREMENT',
};

export default ActionTypes;